version: '3.9'
services:
  attendance_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: attendance_api:latest
    container_name: attendance_api
    ports:
      - "2000:2000"
    restart: always
    volumes:
      - "/opt/attendance_api/log:/app/log"