// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAttendance = "attendance"

// Attendance mapped from table <attendance>
type Attendance struct {
	ID                 int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmpNo              string     `gorm:"column:emp_no;not null" json:"emp_no"`
	CheckIn            *time.Time `gorm:"column:check_in" json:"check_in"`
	CreatedAt          *time.Time `gorm:"column:created_at" json:"created_at"`
	Description        *string    `gorm:"column:description" json:"description"`
	Status             *int32     `gorm:"column:status" json:"status"`
	LateCount          *int32     `gorm:"column:late_count" json:"late_count"`
	AdmissionTimeLimit *string    `gorm:"column:admission_time_limit" json:"admission_time_limit"`
	TimeOutLimit       *string    `gorm:"column:time_out_limit" json:"time_out_limit"`
	Latitude           *string    `gorm:"column:latitude" json:"latitude"`
	Longitude          *string    `gorm:"column:longitude" json:"longitude"`
	Selfie             *[]byte    `gorm:"column:selfie" json:"selfie"`
}

// TableName Attendance's table name
func (*Attendance) TableName() string {
	return TableNameAttendance
}
